### ISSUE TITLE
Odd behavior on GS60 Ghost keyboard (fedora 22)

### ISSUE THREAD

**Issue by Wildcarde** [bparker06/msi-keyboard#1]
You can successfully get this building on Fedora 22 as long as you install qt5-devel and replace 'qmake' with 'qmake-qt5'.  however some of the lighting behaviors don't line up to the profile this code is written around. ie, wave seems to start the demo lighting mode, breathing will allow you to set a 3 region color but won't actually breathe. Things seem to 'stick' if you run the same commands multiple times however, overall it's functional but if I can figure out what's different with the gs60 keyboard I'll try and send a patch over.

**Comment by nomasteryoda** [comment]
First I'd like to thank bparker06 for writing this code... Most Excellent!!!

To Wildcarde,
I have struggled with making nodejs / npm install msi-keyboard  work on  an ongoing basis since ware-fractal came out with the code. When they did that, I was quite happy as just boring white or always on was not something I needed. Nonetheless, it was amazing to finally have control without consuming RAM just to flip some switches.

I just discovered it in the Arch AUR, installed and I've made aliases to different modes - say kbow for the red-purple-sky mode and I too found I need to issue the command 2 times for the mode to "stick" as you put it.

**Comment by bparker06** [comment]
That is strange... I have a gs60 ghost pro 4k (6th-gen), and also tried the program on a 5th gen, and they both work the first time without having to run it more than once, using the example command in the README. Unfortunately I'm not sure how to reproduce the issues you're seeing; the lighting modes were taken from the nodejs version so it's possible that you might see the same behavior with that program as well.
